name: Hylo
options:
  bundleIdPrefix: com.hyloapp
targets:
  Hylo:
    type: application
    platform: iOS
    deploymentTarget: "16.1"
    sources:
      - path: .
        excludes:
          - ".github"
          - "project.yml"
          - "README.md"
          - "*.md"
    info:
      path: Info.plist
    settings:
      GENERATE_INFOPLIST_FILE: NO
      INFOPLIST_FILE: Hylo/Info.plist
      CURRENT_PROJECT_VERSION: "1"
      MARKETING_VERSION: "1.0"
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
